// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRJAF1_24iAzE2YKgnyVJuev532Ryb9g',
    appId: '1:150699372309:web:9fa97d56dc8e1e167a431c',
    messagingSenderId: '150699372309',
    projectId: 'evently-app-c16-61fd4',
    authDomain: 'evently-app-c16-61fd4.firebaseapp.com',
    storageBucket: 'evently-app-c16-61fd4.firebasestorage.app',
    measurementId: 'G-0R0Q797VFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNk0cGp1MRg_qa4bqLq5mYExMFeEbHbms',
    appId: '1:150699372309:android:e080c5821d8a36e27a431c',
    messagingSenderId: '150699372309',
    projectId: 'evently-app-c16-61fd4',
    storageBucket: 'evently-app-c16-61fd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMuZXGkcXEWLCxm2sfJNf82WA5C0gicpc',
    appId: '1:150699372309:ios:2326a34e2dffe00d7a431c',
    messagingSenderId: '150699372309',
    projectId: 'evently-app-c16-61fd4',
    storageBucket: 'evently-app-c16-61fd4.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApplication',
  );
}
